### PR TITLE
Add an ExampleService as minimal example and to test backpressure

### PR DESCRIPTION
**Pull request by velvia**
as well as some additional comments.

### CODE REVIEW

**Comment by velvia** [comment]
@rjmac and others: I'm going to add a really quick method to configure the Pool options from a Typesafe config, cuz that logic probably shouldn't be repeated in multiple services.

**Comment by kaidamasaki** [comment]
LGTM

**Comment by rjmac** [comment]
LGTM too, though the configuration thing won't give very good error messages in the case where something's wrong (in particular, it won't tell the full path to the thing that failed, if the `Config` given is extracted from some large config system).

**Comment by velvia** [comment]
@rjmac true.
I'm going to go ahead and merge it, as would like to get the changes deployed soon.  Thanks.

**Pull request merged**
